(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-auto-save t)
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(auto-save-default nil)
 '(auto-save-file-name-transforms
   (quote
    ((".*" "/var/folders/nr/w1wqbdbd3lzf7t0rxs0py36m0000gn/T/" t))))
 '(auto-save-interval 20)
 '(auto-save-list-file-prefix nil)
 '(auto-save-timeout 1)
 '(background-color "#ffffd7")
 '(background-mode light)
 '(blink-cursor-mode t)
 '(c-basic-indent 2)
 '(column-number-mode 1)
 '(cursor-color "#626262")
 '(custom-safe-themes
   (quote
    ("282606e51ef2811142af5068bd6694b7cf643b27d63666868bc97d04422318c1" "90edd91338ebfdfcd52ecd4025f1c7f731aced4c9c49ed28cfbebb3a3654840b" "f0b0710b7e1260ead8f7808b3ee13c3bb38d45564e369cbe15fc6d312f0cd7a0" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" "6a37be365d1d95fad2f4d185e51928c789ef7a4ccf17e7ca13ad63a8bf5b922f" default)))
 '(diff-hl-margin-mode t)
 '(diff-hl-side (quote right))
 '(ecb-options-version "2.40")
 '(ecb-source-path (quote (("/" "/"))))
 '(ecb-windows-width 0.25)
 '(fci-rule-color "#383838")
 '(flycheck-rubocop-lint-only t)
 '(foreground-color "#626262")
 '(fringe-mode -1 nil (fringe))
 '(global-ede-mode t)
 '(global-font-lock-mode 1)
 '(global-hl-line-mode t)
 '(global-linum-mode nil)
 '(grep-find-ignored-files nil)
 '(helm-ag-insert-at-point (quote symbol))
 '(helm-ag-use-grep-ignore-list t)
 '(helm-buffer-max-length 60)
 '(helm-do-grep-preselect-candidate t)
 '(helm-grep-ignored-files
   (quote
    (".#*" "*.o" "*~" "*.bin" "*.lbin" "*.so" "*.a" "*.ln" "*.blg" "*.bbl" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.dfsl" "*.pfsl" "*.d64fsl" "*.p64fsl" "*.lx64fsl" "*.lx32fsl" "*.dx64fsl" "*.dx32fsl" "*.fx64fsl" "*.fx32fsl" "*.sx64fsl" "*.sx32fsl" "*.wx64fsl" "*.wx32fsl" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" "*.pg" "*.tp" "*.vr" "*.cps" "*.fns" "*.kys" "*.pgs" "*.tps" "*.vrs" "*.pyc" "*.pyo")))
 '(highlight-indentation-offset 2)
 '(indent-tabs-mode nil)
 '(javascript-indent-level 2)
 '(js-indent-level 2)
 '(line-number-mode 1)
 '(locale-coding-system (quote utf-8) t)
 '(menu-bar-mode nil)
 '(mode-line-default-help-echo nil)
 '(mode-line-format
   (quote
    ("%e" mode-line-front-space mode-line-mule-info mode-line-client mode-line-modified mode-line-remote mode-line-frame-identification mode-line-buffer-identification sml/pos-id-separator mode-line-position smartrep-mode-line-string
     (vc-mode vc-mode)
     sml/pre-modes-separator mode-line-misc-info mode-line-end-spaces)))
 '(mode-line-in-non-selected-windows t)
 '(nav-width 30)
 '(ns-pop-up-frames nil)
 '(nxml-attribute-indent 2)
 '(nxml-child-indent 2)
 '(package-selected-packages
   (quote
    (markdown-mode haml-mode flymake-php php+-mode php-mode yaml-mode web-mode scss-mode geiser yari inf-ruby ruby-tools json-mode js2-mode rainbow-mode elisp-slime-nav rainbow-delimiters coffee-mode key-chord company helm-ag helm-descbinds helm-projectile helm smex ido-ubiquitous flx-ido vkill exec-path-from-shell zop-to-char zenburn-theme volatile-highlights undo-tree smartrep smartparens operate-on-number move-text magit projectile ov guru-mode grizzl god-mode gitignore-mode gitconfig-mode git-timemachine gist flycheck expand-region epl easy-kill diminish diff-hl discover-my-major dash browse-kill-ring anzu ace-window)))
 '(prefer-coding-system (quote utf-8))
 '(projectile-global-mode t)
 '(projectile-switch-project-action (quote projectile-dired))
 '(rbenv-show-active-ruby-in-modeline t)
 '(redisplay-dont-pause t t)
 '(ring-bell-function (quote ignore))
 '(rspec-use-bundler-when-possible nil)
 '(rspec-use-zeus-when-possible nil)
 '(ruby-insert-encoding-magic-comment nil)
 '(scroll-conservatively 10000)
 '(scroll-margin 1)
 '(scroll-preserve-screen-position 1)
 '(scroll-step 1)
 '(semantic-mode 1)
 '(set-default-coding-systems (quote utf-8))
 '(set-language-environment (quote utf-8))
 '(set-selection-coding-system (quote utf-8))
 '(set-terminal-coding-system (quote utf-8))
 '(setq-default truncate-lines t)
 '(show-paren-mode t)
 '(sml/use-projectile-p (quote before-prefixes))
 '(sml/vc-mode-show-backend t)
 '(sp-autoescape-string-quote nil)
 '(sp-autoinsert-if-followed-by-same 1)
 '(sp-autoskip-closing-pair (quote always))
 '(tab-width 2)
 '(tabbar-background-color "#8FB28F")
 '(tabbar-mode t nil (tabbar))
 '(tabbar-separator (quote ("|")))
 '(tool-bar-mode nil)
 '(url-proxy-services (quote (("https" . "127.0.0.1:8888"))))
 '(utf-translate-cjk-mode nil)
 '(vc-annotate-background "#2B2B2B")
 '(vc-annotate-color-map
   (quote
    ((20 . "#BC8383")
     (40 . "#CC9393")
     (60 . "#DFAF8F")
     (80 . "#D0BF8F")
     (100 . "#E0CF9F")
     (120 . "#F0DFAF")
     (140 . "#5F7F5F")
     (160 . "#7F9F7F")
     (180 . "#8FB28F")
     (200 . "#9FC59F")
     (220 . "#AFD8AF")
     (240 . "#BFEBBF")
     (260 . "#93E0E3")
     (280 . "#6CA0A3")
     (300 . "#7CB8BB")
     (320 . "#8CD0D3")
     (340 . "#94BFF3")
     (360 . "#DC8CC3"))))
 '(vc-annotate-very-old-color "#DC8CC3")
 '(web-mode-attr-indent-offset 2)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-auto-indentation nil)
 '(web-mode-enable-current-column-highlight nil)
 '(web-mode-enable-current-element-highlight nil)
 '(web-mode-enable-engine-detection t)
 '(web-mode-enable-inlays t)
 '(web-mode-enable-part-face nil)
 '(web-mode-enable-whitespace-fontification nil)
 '(web-mode-indent-style 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 0)
 '(yas-global-mode t nil (yasnippet)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#3F3F3F" :foreground "#DCDCCC" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Input Mono"))))
 '(flycheck-error-list-highlight ((t (:inherit default))))
 '(highlight-indentation-current-column-face ((t (:background "disabledControlTextColor"))))
 '(highlight-indentation-face ((t (:background "disabledControlTextColor"))))
 '(hl-line ((t (:stipple nil :background "#2B2B2B"))))
 '(linum ((t (:background "black" :foreground "cyan"))))
 '(linum-highlight-face ((t (:background "cyan" :foreground "black"))))
 '(magit-section-title ((t (:background "brightblack" :foreground "#F0DFAF" :weight bold))))
 '(mode-line ((t (:background "#5F7F5F" :foreground "gray60" :inverse-video nil :box (:line-width -1 :style released-button)))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#E0CF9F" :style released-button)))))
 '(mode-line-inactive ((t (:background "#4F4F4F" :foreground "#E0CF9F" :inverse-video nil :box (:line-width -1 :style released-button)))))
 '(tabbar-default ((t (:inherit variable-pitch :background "#DCDCCC" :foreground "#8FB28F" :height 0.8 :family "Courier Primal"))))
 '(tabbar-modified ((t (:background "brightred"))))
 '(tabbar-selected ((t (:background "#8FB28F" :foreground "#8C5353" :box (:line-width -1 :style pressed-button)))))
 '(tabbar-separator ((t (:background "#3F3F3F" :foreground "#AC7373"))))
 '(tabbar-unselected ((t (:background "#3F3F3F" :foreground "#4C7073" :box (:line-width -1 :style released-button))))))
