(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode t)
 '(c-basic-indent 2)
 '(column-number-mode 1)
 '(ecb-options-version "2.40")
 '(ecb-windows-width 0.25)
 '(fci-rule-color "#383838")
 '(fringe-mode -1 nil (fringe))
 '(global-ede-mode t)
 '(global-font-lock-mode 1)
 '(global-hl-line-mode 1)
 '(global-linum-mode 1)
 '(highlight-indentation-offset 2)
 '(indent-tabs-mode nil)
 '(javascript-indent-level 2)
 '(js-indent-level 2)
 '(js2-basic-offset 2)
 '(line-number-mode 1)
 '(locale-coding-system (quote utf-8) t)
 '(menu-bar-mode nil)
 '(ns-pop-up-frames nil)
 '(prefer-coding-system (quote utf-8))
 '(redisplay-dont-pause t t)
 '(ring-bell-function (quote ignore) t)
 '(scroll-conservatively 10000)
 '(scroll-margin 1)
 '(scroll-preserve-screen-position 1)
 '(scroll-step 1)
 '(semantic-mode 1)
 '(set-default-coding-systems (quote utf-8))
 '(set-language-environment (quote utf-8))
 '(set-selection-coding-system (quote utf-8))
 '(set-terminal-coding-system (quote utf-8))
 '(setq-default truncate-lines t)
 '(show-paren-mode t)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(url-proxy-services (quote (("https" . "127.0.0.1:8888"))))
 '(utf-translate-cjk-mode nil)
 '(vc-annotate-background "#2B2B2B")
 '(vc-annotate-color-map
   (quote
    ((20 . "#BC8383")
     (40 . "#CC9393")
     (60 . "#DFAF8F")
     (80 . "#D0BF8F")
     (100 . "#E0CF9F")
     (120 . "#F0DFAF")
     (140 . "#5F7F5F")
     (160 . "#7F9F7F")
     (180 . "#8FB28F")
     (200 . "#9FC59F")
     (220 . "#AFD8AF")
     (240 . "#BFEBBF")
     (260 . "#93E0E3")
     (280 . "#6CA0A3")
     (300 . "#7CB8BB")
     (320 . "#8CD0D3")
     (340 . "#94BFF3")
     (360 . "#DC8CC3"))))
 '(vc-annotate-very-old-color "#DC8CC3")
 '(web-mode-enable-auto-indentation t)
 '(web-mode-markup-indent-offset 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
