(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-auto-save t)
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(auto-save-file-name-transforms
   (quote
    ((".*" "/var/folders/nr/w1wqbdbd3lzf7t0rxs0py36m0000gn/T/" t))))
 '(auto-save-interval 20)
 '(auto-save-timeout 1)
 '(background-color "#ffffd7")
 '(background-mode light)
 '(blink-cursor-mode t)
 '(c-basic-indent 2)
 '(column-number-mode 1)
 '(cursor-color "#626262")
 '(custom-safe-themes
   (quote
    ("fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" "6a37be365d1d95fad2f4d185e51928c789ef7a4ccf17e7ca13ad63a8bf5b922f" default)))
 '(ecb-options-version "2.40")
 '(ecb-source-path (quote (("/" "/"))))
 '(ecb-windows-width 0.25)
 '(fci-rule-color "#383838")
 '(foreground-color "#626262")
 '(fringe-mode -1 nil (fringe))
 '(global-ede-mode t)
 '(global-font-lock-mode 1)
 '(global-hl-line-mode 1)
 '(global-linum-mode nil)
 '(helm-buffer-max-length 60)
 '(highlight-indentation-offset 2)
 '(indent-tabs-mode nil)
 '(javascript-indent-level 2)
 '(js-indent-level 2)
 '(js2-basic-offset 2)
 '(line-number-mode 1)
 '(locale-coding-system (quote utf-8) t)
 '(menu-bar-mode nil)
 '(nav-width 29)
 '(ns-pop-up-frames nil)
 '(prefer-coding-system (quote utf-8))
 '(redisplay-dont-pause t t)
 '(ring-bell-function (quote ignore) t)
 '(ruby-insert-encoding-magic-comment nil)
 '(scroll-conservatively 10000)
 '(scroll-margin 1)
 '(scroll-preserve-screen-position 1)
 '(scroll-step 1)
 '(semantic-mode 1)
 '(set-default-coding-systems (quote utf-8))
 '(set-language-environment (quote utf-8))
 '(set-selection-coding-system (quote utf-8))
 '(set-terminal-coding-system (quote utf-8))
 '(setq-default truncate-lines t)
 '(show-paren-mode t)
 '(sml/use-projectile-p (quote before-prefixes))
 '(sml/vc-mode-show-backend t)
 '(sp-autoescape-string-quote nil)
 '(sp-autoinsert-if-followed-by-same 0)
 '(tab-width 2)
 '(tabbar-background-color "brightblack")
 '(tabbar-mode t nil (tabbar))
 '(tabbar-separator (quote ("|")))
 '(tool-bar-mode nil)
 '(url-proxy-services (quote (("https" . "127.0.0.1:8888"))))
 '(utf-translate-cjk-mode nil)
 '(vc-annotate-background "#2B2B2B")
 '(vc-annotate-color-map
   (quote
    ((20 . "#BC8383")
     (40 . "#CC9393")
     (60 . "#DFAF8F")
     (80 . "#D0BF8F")
     (100 . "#E0CF9F")
     (120 . "#F0DFAF")
     (140 . "#5F7F5F")
     (160 . "#7F9F7F")
     (180 . "#8FB28F")
     (200 . "#9FC59F")
     (220 . "#AFD8AF")
     (240 . "#BFEBBF")
     (260 . "#93E0E3")
     (280 . "#6CA0A3")
     (300 . "#7CB8BB")
     (320 . "#8CD0D3")
     (340 . "#94BFF3")
     (360 . "#DC8CC3"))))
 '(vc-annotate-very-old-color "#DC8CC3")
 '(web-mode-code-indent-offset 2)
 '(web-mode-enable-auto-indentation t)
 '(web-mode-enable-current-column-highlight nil)
 '(web-mode-enable-current-element-highlight nil)
 '(web-mode-enable-engine-detection t)
 '(web-mode-enable-part-face nil)
 '(web-mode-enable-whitespace-fontification nil)
 '(web-mode-indent-style 2)
 '(web-mode-markup-indent-offset 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(flycheck-error-list-highlight ((t (:inherit default))))
 '(highlight-indentation-current-column-face ((t (:background "black"))))
 '(highlight-indentation-face ((t (:background "black"))))
 '(hl-line ((t (:stipple nil :background "black"))))
 '(linum ((t (:background "black" :foreground "cyan"))))
 '(linum-highlight-face ((t (:background "cyan" :foreground "black"))))
 '(tabbar-default ((t (:inherit variable-pitch :background "gray75" :foreground "gray50" :height 0.8))))
 '(tabbar-modified ((t (:background "brightred"))))
 '(tabbar-selected ((t (:background "cyan" :foreground "black"))))
 '(tabbar-separator ((t (:background "yellow" :foreground "brightblack")))))
