;;osx specific stuff
;; (setq mac-option-modifier 'meta)
;; (setq mac-command-modifier 'hyper)
;; (global-set-key [(hyper a)] 'mark-whole-buffer)
;; (global-set-key [(hyper v)] 'yank)
;; (global-set-key [(hyper c)] 'kill-ring-save)
;; (global-set-key [(hyper x)] 'kill-region)
;; (global-set-key [(hyper s)] 'save-buffer)
;; (global-set-key [(hyper l)] 'goto-line)
;; (global-set-key [(hyper o)] 'find-file)
;; (global-set-key [(hyper f)] 'isearch-forward)
;; (global-set-key [(hyper g)] 'isearch-repeat-)
;; (global-set-key [(hyper .)] 'keyboard-quit)
;; (global-set-key [(hyper q)] 'save-buffers-kill-emacs)
;; (global-set-key [(hyper z)] 'undo)
;; (global-set-key [(hyper shift z)] 'redo)
