(prelude-require-package 'cyberpunk-theme)
(disable-theme 'zenburn)
(setq prelude-whitespace nil)
(setq prelude-guru nil)
(load-theme 'cyberpunk t)
;(load-theme 'solarized-dark t)
;(load-theme 'manoj-dark t)
;(load-theme 'molokai t)
