(setq prelude-guru nil)
(setq company-begin-commands '(self-insert-command))
(setq aw-scope 'frame)
(disable-theme 'zenburn)
(load-theme 'dracula t)
(scroll-bar-mode -1)
                                        ;(setq prelude-whitespace nil)
                                        ;(setq flx-ido-threshhold 1000)
                                        ; (flx-ido-mode -1)         ;;turn threshold off if this is enabled


;; Color Palette
;;       (fg1 "#f8f8f2")
;;       (fg2 "#e2e2dc")
;;       (fg3 "#ccccc7")
;;       (fg4 "#b6b6b2")
;;       (bg1 "#282a36")
;;       (bg2 "#373844")
;;       (bg3 "#464752")
;;       (bg4 "#565761")
;;       (bg5 "#44475a")
;;       (key2 "#0189cc")
;;       (key3 "#ff79c6")
;;       (builtin "#ffb86c")
;;       (keyword "#ff79c6")
;;       (const   "#8be9fd")
;;       (comment "#6272a4")
;;       (func    "#50fa7b")
;;       (str     "#f1fa8c")
;;       (type    "#bd93f9")
;;       (var     "#f8f8f2")
;;       (warning "#ffb86c")
;;       (rainbow-1 "#f8f8f2")
;;       (rainbow-2 "#8be9fd")
;;       (rainbow-3 "#bd93f9")
;;       (rainbow-4 "#ff79c6")
;;       (rainbow-5 "#ffb86c")
;;       (rainbow-6 "#50fa7b")
;;       (rainbow-7 "#f1fa8c")
;;       (rainbow-8 "#0189cc")
;;       (rainbow-9 "#ff5555")
;;       (eph-verbatim "#f1fa8c")
;;       (eph-code "#ff79c6")
